version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9  # Python base image to use

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt || pip install pytest  # If requirements.txt exists

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest || echo "No tests found"

  build-docker:
    docker:
      - image: docker:latest  # Use Docker image for building and pushing
    steps:
      - setup_remote_docker:
          version: 20.10.7  # Ensure you use the correct version of Docker
      - checkout
      - run:
          name: Ensure bin/invoicer Exists
          command: |
            mkdir -p bin
            echo '#!/bin/bash\necho "Hello, Invoicer!"' > bin/invoicer
            chmod +x bin/invoicer
      - run:
          name: Build Docker Image
          command: |
            docker build -t invoicer:latest .  # Corrected tag format
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push invoicer:latest  # Corrected tag format

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker:
          requires:
            - test
