version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building the code..."
      - run: npm install

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running unit tests..."
      - run: npm test

  docker-build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t kaysan98/invoicer .
          docker push kaysan98/invoicer

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test
      - docker-build
