version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Python base image to use
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt || pip install pytest  # If requirements.txt exists

  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest || echo "No tests found"

  build-docker:
    docker:
      - image: docker:latest  # Use Docker image for building and pushing
    steps:
      - setup_remote_docker:
          docker_layer_caching: true  # Enable Docker layer caching to speed up builds
      - checkout
      - run:
          name: Ensure bin/invoicer Exists
          command: |
            mkdir -p bin
            echo '#!/bin/bash\necho "Hello, Invoicer!"' > bin/invoicer
            chmod +x bin/invoicer

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/invoicer:latest .

      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKER_USERNAME/invoicer:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker
