version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building the code..."
      - run: npm install

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running unit tests..."
      - run: npm test

  docker-build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.7'  # Ensure Docker version compatibility
          docker_layer_caching: true
          docker_sock: /var/run/docker.sock
      - run: echo "Docker setup complete"
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker --version
      - run: docker build -t kaysan98/invoicer .
      - run: docker push kaysan98/invoicer

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
