version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install Flask==2.0.1
            pip install requests==2.26.0
            pip install pytest==6.2.5

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run unit tests
          command: pytest tests/  # Change this if your tests are in a different folder

  build-docker:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t kaysan98/invoicer .

  push-docker:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push kaysan98/invoicer

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker:
          requires:
            - test
      - push-docker:
          requires:
            - build-docker
