version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

  python-executor:
    docker:
      - image: circleci/python:3.8

  docker-executor:
    docker:
      - image: docker:20.10

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build Application
          command: echo "Building application..."

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: echo "Running unit tests..."

  build-docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t invoicer:latest .
      - run:
          name: Verify Image Build
          command: docker images | grep invoicer

  push-docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Docker Image
          command: docker tag invoicer:latest $DOCKERHUB_USERNAME/invoicer:latest
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/invoicer:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker:
          requires:
            - test
      - push-docker:
          requires:
            - build-docker
