version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: List files in the project directory
          command: ls -al /home/circleci/project
      - run:
          name: Install dependencies
          command: npm install

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running unit tests..."
      - run: npm test

  docker-build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: '20.10.7'
          docker_layer_caching: true
      - run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t kaysan98/invoicer .
          docker push kaysan98/invoicer

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker-build:
          requires:
            - test
