version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building application..."
      - run: mkdir -p bin
      - run: echo '#!/bin/bash\necho "Hello, this is invoicer!"' > bin/invoicer
      - run: chmod +x bin/invoicer

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running unit tests..."

  build-docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the invoicer file
          command: |
            mkdir -p bin
            echo '#!/bin/bash\necho "Hello, this is invoicer!"' > bin/invoicer
            chmod +x bin/invoicer
      - run:
          name: Verify invoicer file
          command: ls -la bin/invoicer
      - run:
          name: Build Docker Image
          command: docker build -t invoicer:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push invoicer:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker
