version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Change if needed

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt || pip install pytest  # Install if requirements.txt exists

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: pytest || echo "No tests found"

  build-docker:
    docker:
      - image: docker:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/invoicer:latest .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKERHUB_USERNAME/invoicer:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - test
      - build-docker:
          requires:
            - test
